USE winter_activity_db;


INSERT INTO resorts (name, address, phone, url, lat, lon, policy, overview, pic1, pic2, pic3, pic4, pic5) VALUES 
("Mt. Baker Ski Area","Mt Baker Hwy, Deming, WA 98244", "360.734.6771", "https://www.mtbaker.us/", 48.8572916, -121.6666619,"ACCESS TO THE SKI AREA IS PROHIBITED IF YOU HAVE OR ARE EXPERIENCING SYMPTOMS OF COVID-19. Your presence at the ski area during the COVID-19 pandemic is AT YOUR OWN RISK. By choosing to be here you acknowledge and ACCEPT THE RISKS associated with COVID-19.IF YOU ARE UNWILLING OR UNABLE to comply with COVID-19 policies, you agree to LEAVE THE SKI AREA IMMEDIATELY.  YOU ARE SOLELY RESPONSIBLE FOR COMPLYING with Ski Area and Washington State COVID-19 policies.", "Whilst it packs a lot in, Mount Baker Washington is only a smallish ski resort with 1,000 acres (405 hectares) of terrain and a vertical drop of only 1,588 ft. The Mt Baker ski area has 10 lifts, of which 8 are slow quad chairs.", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315241/Mt%20Baker/baker6_fbf9rr.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315241/Mt%20Baker/baker1_swyxac.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315242/Mt%20Baker/baker2_zdo0hk.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315241/Mt%20Baker/baker3_rhheau.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315241/Mt%20Baker/baker5_zgofhp.jpg"),

("The Summit at Snoqualmie","1001 WA-906, Snoqualmie Pass, WA 98068","425.434.7669", "https://summitatsnoqualmie.com/", 47.42044, -121.4211049, "Face coverings will be required for all guests and team members indoors, in lift lines, on chairs, and any outdoor spaces where physical distancing cannot be maintained. Social distancing measures will be in place in all parts of our business. All indoor spaces will be adjusted to increase physical distancing between individuals and parties. Indoor capacity will be limited. All team members will undergo health screenings prior to every shift. Sneeze guards will be placed at point-of-sale locations. Hand sanitizer will be available throughout the resort. Anyone experiencing COVID-19 symptoms, such as a fever or cough, are asked not to visit the resort. Cashless transactions only." , "Seattle's Home Mountain features four unique mountain areas right in the heart of the Cascades. The four areas include nearly 2,000 skiable acres, 25 lifts, and the most night skiing in the U.S.", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315285/Snoqualmie%20Pass/snoqualmie5_uh6swg.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315285/Snoqualmie%20Pass/snoqualmie6_er9g4u.png", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315284/Snoqualmie%20Pass/snoqualmie3_np6qwx.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315283/Snoqualmie%20Pass/snoqualmie1_zfp0b1.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315283/Snoqualmie%20Pass/snoqualmie4_syycfj.jpg"),

("Crystal Mountain Resort","33914 Crystal Mtn Blvd, Enumclaw, WA 98022" ,"360.663.2265" , "https://www.crystalmountainresort.com/", 46.9352963, -121.476942, "You must wear a mask during your visit and practice social distancing while in common areas. Please make sure your mask covers both your mouth and nose. If you’re feeling ill/feverish/symptomatic please stay home and visit only when you are well. Plexiglass has been installed at key transaction centers as additional protection when keeping 6-feet is not possible. The Mt. Rainier Gondola will load at a reduced rate with your safety in mind, and you will only be permitted to ride with the group that you arrived with.Chairlift operation plans are still being developed, but will likely include a limit on the number of non-familial riders that can be seated on a given chair." , "For many of us, the mountain has long been a refuge. In our busy, modern era we often feel chronically rushed, heavily trafficked and way too plugged in. Yet, when the storms hit or the peaks are out, our mountains become our church. Our spirits are lifted to a place of reverence and awe. We feel moments, we see the landscape and we truly experience the natural environment. We find community that shares the same perspective. We feel more like who we are and who we want to be. With open space, expansive terrain and powerful views, Crystal is that place. Here the mountain towers in a paradise valley at the end of the road. Thriving community exists in our parking lot and in our ski bars. True Pacific Northwest shines through, even in the fog or in the clouds.", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315209/Crystal%20Mountain/crystal1_y9asis.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315210/Crystal%20Mountain/crystal3_aewrrg.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315209/Crystal%20Mountain/crystal2_govmo3.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315209/Crystal%20Mountain/crystal6_kjylbu.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315209/Crystal%20Mountain/crystal7_xq6j7v.jpg"), 

("Stevens Pass Resort", "US-2, Skykomish, WA 98288", "206.812.4510", "https://www.stevenspass.com/site", 47.7448119, -121.0890197, "Face coverings will be required to access our mountain and we have re-imagined our resort experience to allow for physical distancing. For your safety, we are managing on-mountain access this season. Reservations will be required, and our pass holders will get priority access. For your safety, all transactions will will be cashless (unless required by local regulations)", "Stevens Pass is a place that feeds our thirst for adventure. While each person experiences Stevens Pass uniquely, we do have one thing in common: we are all part of the snow-centric Stevens Pass family, and we are pure Pacific Northwest. We have a shared passion for skiing and riding with friends, family and even that random person sitting next to you on the lift. Imagine a special place with deep powder, rolling groomed runs to steep slopes, surrounded by trees and nestled into the mountains. That’s Stevens Pass. A picture-perfect ski area on a blue bird day and a place that sees rapid replenishment of snowpack with many series of winter storms. It is home to a community of full-time, part-time and first-time winter crusaders enjoying the very best of the Cascades – from numerous bowls, glades and faces to extensive lighted terrain for skiing and riding well into the evening. It’s a place that connects us to what we love most – skiing and riding. With an annual snowfall averaging 460 feet each year, 1,125 acres of diverse skiable terrain, it’s no wonder everyone keeps coming back for more.", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315301/Stevens%20Pass/stevens2_e1dzas.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315300/Stevens%20Pass/stevens3_cbe3rm.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315300/Stevens%20Pass/stevens6_sidehu.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315301/Stevens%20Pass/stevens5_zhlccf.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315298/Stevens%20Pass/stevens4_hrwzxs.jpg"), 

("49 Degrees North Mountain Ski & Snowboard Resort","3311 Flowery Trail Rd, Chewelah, WA 99109","509.935.6649", "http://www.ski49n.com/", 48.3011076, -117.5651205, "Social distancing will be encouraged for all guests and employees. Capacity in our indoor spaces will likely be limited throughout the season. We expect to be serving food and beverages, but seating may be limited. 49 Degrees North has over 2,300 skiable acres and multiple lift access points, which makes it easier to find your own space on the mountain. We will monitor the number of daily visitors, but we do not see the need to limit day ticket availability at this time. Keep in mind that weekdays are a great option for those looking to avoid crowds. We also recommend purchasing a season pass for the most consistent access to the mountain. Masks/face coverings will be required for both staff and guests while in any indoor space, except while seated and dining in a designated area. Masks/face coverings will also be required in outdoor areas where social distancing is not possible. This will likely include areas such as Ticket Window lines, lift lines, chairlift unloading zones, or other more congested spaces.", "49 Degrees North is a favorite with locals in northeast Washington State. You will find 2,325 skiable acres on Chewelah Peak, with 54 runs serviced by five lifts. The addition of 12 cut runs and the gladed areas of East Basin have doubled the ski terrain. The vertical is around 1,850 feet. The Chair 2 terrain park is one of the longest in the Northwest.", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315118/49%20North/49_4_omfhtt.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315120/49%20North/49_6_kxom57.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315117/49%20North/49_5_csivd8.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315117/49%20North/49_3_tzhlrx.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315117/49%20North/49_2_e4cfdo.jpg"), 

("White Pass Ski Area", "48935 US Hwy 12, Naches, WA 98937", "509.672.3100", "http://skiwhitepass.com/", 46.6372999,-121.394145, "Your car is your new Day Lodge - access to our lodges will be limited. No lockers or bag storage will be available. Everything must stay in your vehicle. Food & Beverage services will require reservations on busy days (reservations available on-site only) Rental will be open and access will be metered on busy days to control capacity. Face coverings will be required at all times - protect yourself and protect others", "With majestic views of Mt. Rainier, White Pass provides terrain for skiers and riders of every ability. Explore steeper terrain off the Great White Express, or explore Paradise Basin on the Couloir Express and Basin Quads. Our mid-mountain Lodge, The High Camp, is the perfect meeting point for brunch or an afternoon bbq and beer. White Pass features slope side lodging at the Village Inn, on-site Child Care, multiple dining options, full-service Learning, Nordic, Rental & Retail Centers, all found in a relaxed family atmosphere. Leave the city behind and escape to White Pass!", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315315/White%20Pass/wp4_kgfyk3.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315315/White%20Pass/wp2_ujpcuo.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315315/White%20Pass/wp5_snpwy4.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315315/White%20Pass/wp6_sv5k4x.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315317/White%20Pass/wp1_xvejj2.jpg"), 

("Mission Ridge Ski & Board Resort","7500  Mission Ridge Rd, Wenatchee, WA 98801","509.663.6543", "https://www.missionridge.com/", 47.2924693, -120.4020597, "We ask our guests for their assistance and support in our effort to implement health and safety guidelines for everyone’s benefit. Help them be the reason we have a season by: Maintaining 6 feet of social distancing. Washing hands frequently with soap and water. Wearing a face covering that aligns with CDC recommendations whenever physical distancing cannot be achieved. This includes both indoor and outdoor spaces, except when eating or drinking. Staying at home if you are at risk or are sick. Seeking testing immediately if you have symptoms.","Located only 12 miles from Wenatchee, Washington, Mission Ridge is built into a basin on the eastern side of the Cascade Mountains and known for having 300 days of sunshine annually compared to other mountains in Washington.  Mission Ridge features 2,000 accessible acres with a vertical rise of 2,250 feet, and 36 designated trails serviced by four lifts and two rope tows. With a terrain rating of 10% beginner, 60% intermediate and 30% advanced, skiers and riders have access to groomers, chutes, bowls, and backcountry for those who prefer the more extreme.", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315225/Mission%20Ridge/mission1_v76v18.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315225/Mission%20Ridge/mission6_jftxuk.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315224/Mission%20Ridge/mission5_zbmohg.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315224/Mission%20Ridge/mission2_r5vxcx.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315224/Mission%20Ridge/mission3_aooxv0.jpg"), 

("Mt. Spokane Ski and Snowboard","29500 N Mt. Spokane Park Dr, Mead, WA 99021","509.238.2220", "http://www.mtspokane.com/", 47.9213856, -117.0986047, "The team is hard at work preparing for the upcoming season, that is going to look just a bit different than what we are use to.  However, one thing is for sure....your Mt. Spokane will operate properly, safely and providing you with the best experience possible.  The health and safety of our guests and employees remain of the utmost importance. We are committed to the winter season and we are anxious to make some turns.  For many of us here, like you, we still had some turns that were itching to be made. We will continue to work with the National Ski Areas Association, Pacific Northwest Ski Areas Association, and local health officials to formulate our re-opening plan. Be sure you are ready...a season pass allows you a guaranteed spot on the mountain!  No reservations required and direct to lift access", "Mount Spokane State Park spans over 13,900 acres. The beauty of Mount Spokane is that it offers year-round recreation like nordic skiing, snowshoeing, snowmobiling, camping, horseback riding, biking, and hiking trails, berry picking, and much more within just an hour drive from Downtown Spokane! The summit of the mountain reaches 5,883 feet and boasts insane panoramic views. Mount Spokane State Park has over 100 miles of trails to explore on your next hiking adventure. Mountain bikers and equestrian lovers have over 80 miles of trails to explore for long rides. Moose can be found on the mountain so, keep your eyes open for them during your adventure. Skiing and snowboarding are a highlight of the mountain during the winter with nearly 37 miles of nordic ski trails through varying terrain for all types of skiers. During the winter, the park receives about 25 feet of snow. More than 18 miles of groomed trails are also available for snowmobilers. Snowshoeing, back-country skiing and snowboarding can also be enjoyed on other designated trail systems in the park that aren’t groomed.", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315264/Mount%20Spokane/ms1_zxc8bm.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315264/Mount%20Spokane/ms4_qkujfu.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315264/Mount%20Spokane/ms6_zzmqau.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315264/Mount%20Spokane/ms5_t9wj6x.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315265/Mount%20Spokane/ms2_w0ihe7.jpg"),

 ("Alpental Ski Resort","1001 WA-906, Snoqualmie Pass, WA 98068" ,"425.434.7669" , "https://summitatsnoqualmie.com/alpental", 47.4247946, -121.4182077,"Face coverings will be required for all guests and team members indoors, in lift lines, on chairs, and any outdoor spaces where physical distancing cannot be maintained. Social distancing measures will be in place in all parts of our business. All indoor spaces will be adjusted to increase physical distancing between individuals and parties. Indoor capacity will be limited. All team members will undergo health screenings prior to every shift. Sneeze guards will be placed at point-of-sale locations. Hand sanitizer will be available throughout the resort. Anyone experiencing COVID-19 symptoms, such as a fever or cough, are asked not to visit the resort. Cashless transactions only.", "Alpental is synonymous with skiing in the Pacific Northwest. Its deep-rooted history and legendary terrain make this mountain a bucket list item for skiers and riders. The area provides some of the steepest and deepest runs in the region. Take a ride up the infamous Chair 2 and you'll see what we mean. Two intermediate lifts and a magic carpet make Alpental a great place to teach the young ones to rip. Stop by the one of the lodges for a beer or bite when the day is done.", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315173/Alpental/alpental6_gt9w4n.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315172/Alpental/alpental3_ayht4d.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315173/Alpental/alpental1_y1s4cl.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315173/Alpental/alpental5_zn13kx.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315173/Alpental/alpental4_asmxbu.jpg"),
 
 ("Ski Bluewood","Bluewood Road, Dayton, WA 99328" , "509.382.4725", "http://www.bluewood.com/", 46.0824903, -117.853356, "Will operate on the normal schedule for 2020/2021 Season. -Mandatory face coverings in all indoor spaces. Only a limited number of day tickets will be sold each day" , "High atop the Blue Mountains, just 52 miles northeast of Walla Walla in southeast Washington, our ski area occupies the second-highest base elevation (4,545 feet) in the state. Bluewood also has a reputation of possibly having the best snow in the state as well as memorable tree skiing. For those who are unfamiliar with this area, the Blue Mountains rise out of a high-desert region, which provides clear skies and cold, smoke-dry powder. The average annual snowfall is more than 300 inches. The mountain offers nearly 400 skiable acres of lift-serviced terrain for every ability level and interest. With 24 trails, three terrain parks, amazing tree skiing areas and snowcat accessible terrain, we have something for everyone at Bluewood. They are an affordable, family-friendly ski area that really is closer than you think!", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315190/Bluewood/bw2_ukjcdg.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315189/Bluewood/bw3_fraxvq.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315190/Bluewood/bw4_ekwfqp.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315189/Bluewood/bw5_sphenl.jpg", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603315191/Bluewood/bw1_qpbeup.jpg");




INSERT INTO activities (name, slope, about, guide, actImage) VALUES 
("Skiing", 1, "The oldest documented evidence of skiing is found in the region of Norway and Sweden from primitive carvings dating back to 5000 B.C. Until the 1800’s skiing was primarily used only for transport, it was after the turn of the 18th century that it became a recreational sport. Commercially the popularity of skiing holidays took off in the 19th century which increased substantially during the mid-1900s until today. Also called 'downhill skiing', Alpine skiing typically takes place on a piste at a ski resort. It is characterized by fixed-heel bindings that attach at both the toe and the heel of the skier's boot. Ski lifts, including chairlifts, bring skiers up the slope. Backcountry skiing can be accessed by helicopter, snowcat, hiking and snowmobile. Facilities at resorts can include night skiing, après-ski, and glade skiing under the supervision of the ski patrol and the ski school. Alpine skiing branched off from the older Nordic type of skiing around the 1920s when the advent of ski lifts meant that it was no longer necessary to climb back uphill. Alpine equipment has specialized to the point where it can now only be used with the help of lifts.", 
"<b>What equipment do I need to go skiing?</b> 
<p> The bare minimum needed for skiing is a pair of skis, boots and poles; however, there are plenty of other pieces of gear that make it lot safer and more comfortable.</p>
<b> Should I rent or buy ski equipment?</b> 
<p>For your first time skiing it's best to rent equipment to keep the costs down. Almost all ski centres hire out skis, boots, poles, helmets and some even offer waterproof clothing.</p>
<b> How to clip into skis</b>
<p>Once you have your boots on and the correct length poles, head out to a flat area of snow and position your skis perpendicular to any kind of slope. You'll want to put on the lower ski first as this will stop you sliding down the hill when you put the other one on. Put the toe of the boot under the front binding then press down the heel of the boot to you hear a click (use your poles for balance); repeat the process for the second ski and you are ready to go. The binding you have clicked your boot into transfers the power from your body through the boot and into the ski. If you fall over, the bindings will open, releasing your foot to avoid twisting and injury.</p>
<b> Pace yourself</b> 
<p>Doing anything for the first time can be intimidating and exhausting. Warm up, stretch and stick to easier runs in the beginning. You can take on more challenging runs as your confidence and skills grow. Take regular breaks. Be patient. Try not to overdo it in the beginning. Have fun! Skiing or snowboarding is about enjoying time with friends or family, creating memories and soaking in majestic views.</p>
<b>Know when to call it</b> 
<p>Skiing and snowboarding are sports that require physical exertion, balance, dexterity and concentration. A day of skiing or riding can be exhausting, especially if you’ve never done it before. While it may be tempting to ride or ski until last chair, it’s better to call it a day when your legs get tired or you can no longer stay in control. Once you’re done for the day, it’s time to enjoy an après ski treat—you’ll have earned it!</p>", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603583427/Activities/skiing_kiniqi.jpg"),

("Cross Country Skiing", 0,"Cross country skiing is fun…  it’s also fun to learn, healthy, family friendly, accessible, affordable, and offers great variety! Cross country skiing is one of the healthiest recreational activities for both body and soul. You can enjoy the beauty of nature – with its towering trees, mountain vistas, or snow-covered meadows – while experiencing a total body workout. It uses all your muscle groups and is a terrific cardiovascular activity! Plus, you can do it at your pace and according to your fitness level… from smooth gliding on gentle trails to bounding up, over, and down varied terrain.
<b>Family Friendly</b> 
<p>Cross country skiing is a multi-generational activity. Infants and toddlers can ride in a backpack or on a sled… while it’s also gentle for grandparents and great-grandparents. Teenagers who want to go fast can skate ski, a technique that combines the leg motion of ice skating and the arm push of cross country skiing. Even the family dog can join you, as some centers welcome canines on designated dog trails.</p>
<b>Afforable</b> 
<p>A cross country skiing day trip costs an average of $25 for a trail fee and $60 for a trail pass, rental equipment, and a lesson package. And compared with other winter vacations, a cross country ski escape costs much less. A weekend vacation for a family of four – including accommodations, breakfast and dinner, trail fees, rental equipment, and a lesson – is available in New England for under $500. A week’s getaway for a couple at a lodge or ranch in the U.S. or Canadian Rockies – including seven nights lodging, all meals, and skiing – is priced from $2000.</p>", 
"<b> Skiing Etiquette</b> 
<p>When cross country skiing at a ski area, resort, or trail:</p>
<ul>
<li>Help maintain the integrity of the ski tracks by not skiing over them.</li>
<li>Obey posted signs.</li>
<li>Give downhill skiers the right of way.</li>
<li>Fill in your divots and sitz-marks.</li>
<li>Grooming vehicles may be on the trails—use caution.</li>
<li>Return to the lodge by closing.</li>
<li>Remove skis at road crossings.</li>
<li>Stay on the marked trails.</li>
<li>Never ski alone.</li>
<li>Choose trails appropriate to your ability and fitness.</li>
<li>Report any accidents to the nordic center.</li>
</ul>
<b>Do the shuffle</b> 
<p>Having long skinny skis on your feet takes some getting used to, so click into your skis and practice shuffling gently down the trail to get a feel for how they move on the snow. It feels a little like you’re simply walking on the snow.</p>
<b>Shuffle and Glide</b> 
<p>Gliding is the motion that distinguishes cross-country skiing from hiking and snowshoeing. It’s also a big part of the fun. This drill takes a basic shuffle and adds a gliding motion to the mix:</p>
<p>Start by doing the easy shuffle you just learned. After two shuffles, quickly transfer and center your weight onto the front ski, but this time glide on it for a short distance. Keep repeating these steps with a shuffle, shuffle, glide cadence: You’re now doing the basic kick-and-glide motion of classic cross-country skiing.</p>", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603583427/Activities/xc_skiing_cg3f2s.jpg"),

("Snowboarding", 1, "<p>Snowboarding is a winter sport that involves descending a slope that is covered with snow while standing on a board attached to a rider’s feet, using a special boot set onto a mounted binding. The development of snowboarding was inspired by skateboarding, sledding, surfing and skiing. It was developed in the United States in the 1960s to 1970s and became a Winter Olympic Sport in 1998.</p>
<p>Snowboarding has been around since the 1920s, when boys and men would tie plywood or wooden planks from barrels to their feet using clotheslines and horse reins in order to steer themselves down hills. Modern snowboarding began in 1965 when Sherman Poppen, an engineer in Muskegon, Michigan, invented a toy for his daughter by fastening two skis together and attaching a rope to one end so she would have some control as she stood on the board and glided downhill.", "Balancing on a snowboard is easier said done. Snowboarding beginners should start with leg building exercises to strengthen leg muscles. One can practice by standing on one leg and swinging the other leg out in various directions. This should be practiced regularly till you are confident.You must balance your body weight over the center part of your foot’s arch, with the head and hips to be centered too. Both your hands are to be held out a little bit on both sides, but should still be focused at the center of your board. Apart from your arms which are moving on your sides, the next thing to move is your head in the same direction you’re riding.</p> 
<b>Riding and turning a snowboard</b> 
<p>This part is most crucial to practice as it will set you in the right motion if carefully followed, as it constitutes the basic part and focuses on important body movements.</p>
<ul>
<li>Head should be held up and high.</li>
<li>Focus on the direction you want to go.</li>
<li>Your head as well as your shoulders need to be turned in the direction you are riding.</li>
<li>Core muscles should be solely used to turn your snowboard.</li>
<li>When you turn, the speed should be should be same as the speed in which you turn your shoulders</li>
<li>Keep the hips balanced properly in the center of the board.</li>
<li>Feet should be properly strapped into bindings of the board</li>
<li>When you ride heel-side, you should motion your feet towards the front of the snowboard</li>
<li>When you ride toe-side, your feet should face the tail end of your board.</li>
</ul>
<p>Feet movement has a lot of impact. For a toe-side turn, first pressure should be totally on the toes of your front foot and when the turn ends, on the back foot toes. Similarly, for a heel-side turn , begin with putting pressure on the heels of your front foot and later, end it on the heels of your back foot. It’s quite easy once you practice and get the hang of it.
These steps help you understand your body and how it syncs with the snowboard. Practice the above steps, and once learned, combine them all and turn like a professional on your snowboard. Once you have mastered these, you are set to experiment on different snow surfaces on mountains and make progression on this fun activity.</p>
<p>Remember, there is no easy way to learn snowboarding, though the above tips are a great help. However, the key to success lies in practicing and balancing the movements.</p>", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603583425/Activities/snowboarding_by6ksc.jpg"),

("Snow Shoeing", 0, "Snowshoeing is a great winter sport for a wide array of people from old and young, rich or poor, male and female. The best thing about snowshoeing is that anyone can do it. It’s super easy to learn and will enable you to hike over wintry terrain like never before. On top of that, it’s much safer than other winter sports, making it great for kids and those getting older.Snowshoeing is also great for your health. It helps improve cardiovascular health and, according to the SIA, can burn more than 45 percent more calories than walking or running at the same speed. Perhaps even better is that it’s a relatively cheap sport to get into as opposed to snowboarding and skiing. You’ll need fewer pieces of equipment, and the items you will need are generally less expensive than other winter sports. So if you’ve got the time, you pretty much have everything you need to get started.", "The best thing about snowshoeing is that you can really do it anywhere where there is snow on the ground, but there are some places that make more sense than others. If you’re new to the sport, the best place will probably be some kind of state trail that is unkempt and open during the winter. The terrain will be mostly flat, and you can easily trek out for some distance then turn around and come back. Parks or snow-covered golf-courses are also a place to get your feet wet (not literally though). Next, most ski resorts allow snowshoeing on their grounds. This is a great place to try out some more difficult terrain and build endurance for longer hikes. Just remember that skiers get the right of way because it’s easier for you to stop and step off the trail than it is for them. Be respectful! Finally, when you’re feeling confident about your skills, go for a long hike in a national park or forest. These lands will be mostly untouched and feature incredible views and a deep quiet that is perfect for a hike. If you’re feeling really bold, snowshoe out to a beautiful spot and camp for a couple days. As always, remember to plan ahead. Know what to expect from the weather and know a thing or two about that land you plan on hiking. There are all kinds of surprises out there in nature, and you should be prepared to deal with them. Most importantly, make sure to have fun!", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603583425/Activities/snowshoeing_ta8vbh.jpg"),

("Tubing", 1, "Snow tubing is simply a fun, recreational activity that makes use of gravity to transport oneself to the bottom of a slope while riding an inner tube. A steeper run equals higher speed. There is no skill required to be able to snow tube. There is no training required, no practice needed and no muscle strength necessary. As long as you can sit and hold on, you are good to go. Snow tubing can be likened to going down a straight water slide in a tube. To keep the tube sliding in one direction, snow is often built up along each side of a predetermined lane. At the long run out down the hill, riders will be brought to a stop. This activity is somewhat similar to sledding, but the difference is, you have a softer surface to sit on. With a sled, you can drag your arms in the snow to break; but if you do this with a tube, you may just spin downhill because it would be difficult to control its direction.", "<p> Just like any other sledding outing, dress in warm, non-cotton layers and don't forget the snowpants! If you're tubing at a ski hill there will be a rope tow, magic carpet or something similar to get you back up the hill -- so you don't have to worry about sweating on the way up. If you're doing it yourself and have to walk your own tube uphill, wear layers you can easily unzip or take off so you don't overheat on the trek uphill. Stick a length of cordage in your pocket and you can use it as a makeshift leash for hauling the tube uphill. Last but not least: If you're really getting extreme with your tubing or out in icy conditions, helmets are a good idea; some tubing hills require them for children under a given age. (They usually provide the helmets.)</p>
<b>Watch those turns</b> 
<p>Riding up onto the wall of a banked turn is the best thing ever about groomed tubing parks -- but it's easier than you might think to get flung all the way up that wall and over the far side. Smart tubing parks will either build the 'wall' of the turn extra high or put safety netting on top of it, or both -- but it never hurts to watch other tubers of about the same weight take their runs and see how far up the wall they go. If in doubt, keep it slow on the first run and work up to higher speeds later on.</p>
<b>No brakes!</b>  
<p>Snow tubes have no brakes and they're inherently hard to control -- that's part of the fun! But it also means that once you get up to speed, any attempts to steer by dragging your hands and feet can send you into a spin to make the actors of Top Gun jealous. If you start braking right from the start you can keep yourself slow to a certain degree; but if you miss that slim window of opportunity, even the attempt to brake can be dangerous.</p>", "https://res.cloudinary.com/dfsddnvoo/image/upload/v1603583426/Activities/tubing_ahyt4r.jpg");
